name: taller_mecanico
description: A new Flutter project
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_svg: ^2.0.10  # Correct package name
  provider: ^6.1.1
  fluttertoast: ^8.2.2
  firebase_core: ^3.13.0
  firebase_auth: ^5.5.3
  firebase_auth_web: ^5.14.2
  cloud_firestore: ^5.6.7
  google_maps_flutter: ^2.5.0
  
  flutter_web_plugins:
    sdk: flutter
  intl: ^0.20.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  

flutter:
  uses-material-design: true
  assets:
    - assets/images/taller_mecanico.jpg
    - assets/icons/google.svg
    - assets/icons/apple.svg
